// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCur9BU50M_zvAl9Hnsz6GgoASnyx_dRjg',
    appId: '1:202129414783:web:a3c86fe8dde7ef5510fd4a',
    messagingSenderId: '202129414783',
    projectId: 'book-app-3b375',
    authDomain: 'book-app-3b375.firebaseapp.com',
    storageBucket: 'book-app-3b375.appspot.com',
    measurementId: 'G-9YS23D0V1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKnhSYVSFyKzmGW4g3d57JO9VXZAYN3sk',
    appId: '1:202129414783:android:d421c090b8cae2a110fd4a',
    messagingSenderId: '202129414783',
    projectId: 'book-app-3b375',
    storageBucket: 'book-app-3b375.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuiUtqELqhErIzwtolR51twJojzHDS52s',
    appId: '1:202129414783:ios:cfcde6b0c93da2e810fd4a',
    messagingSenderId: '202129414783',
    projectId: 'book-app-3b375',
    storageBucket: 'book-app-3b375.appspot.com',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuiUtqELqhErIzwtolR51twJojzHDS52s',
    appId: '1:202129414783:ios:cfcde6b0c93da2e810fd4a',
    messagingSenderId: '202129414783',
    projectId: 'book-app-3b375',
    storageBucket: 'book-app-3b375.appspot.com',
    iosBundleId: 'com.example.bookly',
  );
}
